/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author User
 */
public class FAddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form FAddEmployee
     */
    public FAddEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        FirstnameTxt = new javax.swing.JTextField();
        LastnameTxt = new javax.swing.JTextField();
        AgeTxt = new javax.swing.JTextField();
        IDCodeTxt = new javax.swing.JTextField();
        KeycodeTxt = new javax.swing.JTextField();
        TimeInOut = new javax.swing.JCheckBox();
        BasicInfo = new javax.swing.JCheckBox();
        EmploymentInfo = new javax.swing.JCheckBox();
        AttendanceData = new javax.swing.JCheckBox();
        AllAccess = new javax.swing.JCheckBox();
        AddButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstnameTxt.setBackground(new java.awt.Color(40, 40, 40));
        FirstnameTxt.setForeground(new java.awt.Color(255, 255, 255));
        FirstnameTxt.setBorder(null);
        getContentPane().add(FirstnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 20));

        LastnameTxt.setBackground(new java.awt.Color(40, 40, 40));
        LastnameTxt.setForeground(new java.awt.Color(255, 255, 255));
        LastnameTxt.setBorder(null);
        getContentPane().add(LastnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 130, 20));

        AgeTxt.setBackground(new java.awt.Color(40, 40, 40));
        AgeTxt.setForeground(new java.awt.Color(255, 255, 255));
        AgeTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AgeTxt.setBorder(null);
        getContentPane().add(AgeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 250, 30, 20));

        IDCodeTxt.setBackground(new java.awt.Color(40, 40, 40));
        IDCodeTxt.setForeground(new java.awt.Color(255, 255, 255));
        IDCodeTxt.setBorder(null);
        getContentPane().add(IDCodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 130, 20));

        KeycodeTxt.setBackground(new java.awt.Color(40, 40, 40));
        KeycodeTxt.setForeground(new java.awt.Color(255, 255, 255));
        KeycodeTxt.setBorder(null);
        getContentPane().add(KeycodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 130, 20));

        TimeInOut.setBackground(new java.awt.Color(40, 40, 40));
        TimeInOut.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        TimeInOut.setForeground(new java.awt.Color(255, 255, 255));
        TimeInOut.setText("Time In / Time Out");
        getContentPane().add(TimeInOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 140, 30));

        BasicInfo.setBackground(new java.awt.Color(40, 40, 40));
        BasicInfo.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        BasicInfo.setForeground(new java.awt.Color(255, 255, 255));
        BasicInfo.setText("Basic Info");
        getContentPane().add(BasicInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 140, 30));

        EmploymentInfo.setBackground(new java.awt.Color(40, 40, 40));
        EmploymentInfo.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        EmploymentInfo.setForeground(new java.awt.Color(255, 255, 255));
        EmploymentInfo.setText("Employment Info");
        getContentPane().add(EmploymentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 140, 30));

        AttendanceData.setBackground(new java.awt.Color(40, 40, 40));
        AttendanceData.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        AttendanceData.setForeground(new java.awt.Color(255, 255, 255));
        AttendanceData.setText("Attendance Data");
        getContentPane().add(AttendanceData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 140, 30));

        AllAccess.setBackground(new java.awt.Color(40, 40, 40));
        AllAccess.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        AllAccess.setForeground(new java.awt.Color(255, 255, 255));
        AllAccess.setText("All Access");
        getContentPane().add(AllAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 140, 30));

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SmallAddButton.png"))); // NOI18N
        AddButton.setBorderPainted(false);
        AddButton.setContentAreaFilled(false);
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 100, -1));

        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SmallCancelButton.png"))); // NOI18N
        CancelButton.setBorderPainted(false);
        CancelButton.setContentAreaFilled(false);
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 100, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AddBG.png"))); // NOI18N
        Background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JCheckBox AllAccess;
    private javax.swing.JCheckBox AttendanceData;
    private javax.swing.JLabel Background;
    private javax.swing.JCheckBox BasicInfo;
    private javax.swing.JButton CancelButton;
    private javax.swing.JCheckBox EmploymentInfo;
    private javax.swing.JTextField FirstnameTxt;
    private javax.swing.JTextField IDCodeTxt;
    private javax.swing.JTextField KeycodeTxt;
    private javax.swing.JTextField LastnameTxt;
    private javax.swing.JCheckBox TimeInOut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
